### PR TITLE
Change paper bug fixes

### LINKED ISSUE #88: Duplicate attributes appear in change paper (with data sets) for branch CR1903
# Overview

When generating the DITA change paper for in-flight branch CR1903, to include data set definitions, the DITA output contains duplicate topics for Attributes which prevents the DITA from being transformed into a PDF.

# Steps to replicate

1. Make sure you have the CR1903 branch ingested.
2. Sign in to the Orchestrator
3. Select the CR1903 branch, click the "Publish" tab
4. Click the generate button next to "Generate change paper (with Data Set definitions)"
5. Open the DITA output in OxygenXML and view the `changes.dita` file

# Expected behaviour

The DITA output should be valid and OxygenXML should be able to transform it into PDF.

# Additional details

The topic elements for Attributes seem to have duplicate ids e.g. `attribute_record_identifier` appears multiple times. There should only be one copy.

Look at the code in `ChangePaper.calculateChanges()`, this should be where the "Changed data set" changes are added.

### LINKED ISSUE #93: Change paper does not include updated description on items on the TEST environment
# Overview

When generating or previewing a change paper on the NHSE TEST environment, updated descriptions do not appear. The reason seems down to the DaisyDiff library throwing this error when comparing HTML text, this error is thrown:

```
Failed comparison: Cannot invoke "net.sf.saxon.event.Receiver.startElement(net.sf.saxon.om.NodeName, net.sf.saxon.type.SchemaType, net.sf.saxon.om.AttributeMap, net.sf.saxon.om.NamespaceMap, net.sf.saxon.s9api.Location, int)" because "this.receiver" is null
```

# Steps to replicate

On the test environment, go to the Orchestrator and preview a change paper for an in-flight branch. It will complete, but any items listed as "Updated descriptions" will show no text. "New" items will show text.

Also note that this does not seem to happen on a local development environment.

# Additional notes

This StackOverflow page could explain what to do to fix it: https://stackoverflow.com/questions/54598683/getting-null-pointer-exception-net-sf-saxon-event-receivingcontenthandler-starte

The `dependencies.gradle` file forces the use of the `xalan` library for `DaisyDiff`, yet it is possible that the wrong dependency is used at runtime on the server. Therefore, in `DaisyDiffHelper`, try and switch round the instantiation from this:

```groovy
//SAXTransformerFactory tf = new org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl()
SAXTransformerFactory tf = (SAXTransformerFactory) SAXTransformerFactory.newInstance()
```

To this:

```groovy
SAXTransformerFactory tf = new org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl()
//SAXTransformerFactory tf = (SAXTransformerFactory) SAXTransformerFactory.newInstance()
```

To test locally, you could try running the build via Docker on your local machine. It is possible that Tomcat could be pulling in a different `SAXTransformerFactory` dependency by mistake. This might help test without need to deploy to TEST (or it might not).

# Related

- #72

### PR DESCRIPTION
**Pull request by pjmonks**
Two fixes around change papers.

# Updated descriptions not appearing

Fixes #93 

Seems to only be a problem on the NHSE Test server, possibly the wrong dependency for `SAXTranformationFactory` was being loaded. Forced the `xalan` library to be used instead, no idea if this works or not  - it hasn't broken anything so far.

# Remove duplicate Data Elements and Attributes

Fixes #88 

When generating the change paper for CR1903, it contains multiple data sets. This repeated some of the Data Elements and Attributes in the summary of changes list because they are shared across multiple data sets e.g. "NHS NUMBER". Forced only unique lists to be used so nothing gets duplicated and breaks the DITA transform.

# Testing

1. Ensure that a Change Paper can be previewed/generated.
2. Ingest the CR1903 branch and generate the DITA change paper for it. Then make sure it can be converted to PDF.

### CODE REVIEW

File: src/main/groovy/uk/nhs/digital/maurodatamapper/datadictionary/publish/DaisyDiffHelper.groovy [hunk 1]
```diff
@@ -38,8 +37,7 @@ class DaisyDiffHelper {
 
     static String diff(String first, String second) throws Exception {
         StringWriter finalResult = new StringWriter()
-        //SAXTransformerFactory tf = new org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl()
-        SAXTransformerFactory tf = (SAXTransformerFactory) SAXTransformerFactory.newInstance()
+        SAXTransformerFactory tf = new TransformerFactoryImpl()
```
Comment (OButlerOcc) [inline src/main/groovy/uk/nhs/digital/maurodatamapper/datadictionary/publish/DaisyDiffHelper.groovy:40]: Looking a little further than this it seems that the previous code called the jvm's version of the object and there might be a difference there?

I may have found a way to test this:

TBA

I'll have a go, if I can't the logic seems sound but I think they're on the same JVM now assuming the testing site has been updated with the testing branch docker code since 2022 which means it might not be the cause.

Edit: testing was inconclusive using java 12 (the old one) does not even build so I'm not sure this is the error we're having.

**Review by OButlerOcc — APPROVED** [review]
Tested creating the broken change paper, works fine, no issues.

tried to test the other one but its a bit inconclusive without having access to the system and I had a brief go at getting docker to run but its not an easy solution with our current system locks. If we need this again I could spend a day on it but not for this pr.

The publish issue does seem fixed, I have no issue with the code and I appreciate the readability comments. If the dependancy fix works I'll be amazed but pleased. Test it in production
