### PR TITLE
gh-111 More preview fixes

### LINKED ISSUE #111: More preview issues
# Overview

Update the Orchestrator preview to fix these issues:

- NHSDigital/DataDictionaryPublication#515
- NHSDigital/DataDictionaryPublication#551
- NHSDigital/DataDictionaryPublication#552
- NHSDigital/DataDictionaryPublication#554
- NHSDigital/DataDictionaryPublication#556

# Notes

- Attribute pages should not show Default Codes, only National Codes
- Retired Data Sets should not show specifications, only the retired (short) description
- Retired Attributes should not show Attribute Terminologies
- Retired Data Elements should not show code sets
- Retiring a single term in an Attribute Terminology/Code Set should put text in brackets that it is retired (and when)

### PR DESCRIPTION
**Pull request by pjmonks**
Fixes #111 

Various fixes to the Orchestrator preview:

- Attribute pages should not show Default Codes, only National Codes
- Retired Data Sets should not show specifications, only the retired (short) description

image

- Retired Attributes should not show Attribute Terminologies

image

- Retired Data Elements should not show code sets

image

- Retiring a single term in an Attribute Terminology/Code Set should put text in brackets that it is retired (and when)

image

### CODE REVIEW

File: src/main/groovy/uk/nhs/digital/maurodatamapper/datadictionary/NhsDDCode.groovy [hunk 1]
```diff
@@ -67,14 +72,44 @@ class NhsDDCode {
 
     }
 
+    String getDescription() {
+        String description = webPresentation ?: definition
+
+        // Some of the ingested branches seem to already contain the "(Retired [date])" text in the definition, don't duplicate it
```
Comment (OButlerOcc) [inline src/main/groovy/uk/nhs/digital/maurodatamapper/datadictionary/NhsDDCode.groovy:78]: well thats annoying, good catch

**Review by OButlerOcc — APPROVED** [review]
Tested fine and working, all the expected changes show up in the orchestrator

Code looks fine, mostly small bug fixes but well done on catching that already retired bit
