### PR TITLE
Feature/gh 124 preview bugs

### LINKED ISSUE #126: Do not show "Format/Length" on Data Elements that are retired
# Description

When a Data Element is retired, the "Format/Length" section should be removed - in page output but also change papers. See https://www.datadictionary.nhs.uk/data_elements/retired/a_and_e_initial_assessment_time.html as an example.

# Related

- NHSDigital/DataDictionaryPublication#554

### LINKED ISSUE #127: Retired terms do not show dates correctly
# Description

Terms that are retired need to display the correct retired date.

- Change the "Term" profile to store retired dates correctly
- Update `NhsDDCode.getDescription()` to correctly fetch and format retired dates

# Related

- NHSDigital/DataDictionaryPublication#556

### PR DESCRIPTION
**Pull request by pjmonks**
Fixes #127 
Fixes #126 

Minor data dictionary page preview fixes.

- Hides the "Format/Length" section on a Data Element page when the Data Element is retired
- If a National/Default Code (Term) is marked as retired, the retired date is rendered as-is correctly. This is because it is stored as a string, so there are no guarantees it is a structured date value.

### CODE REVIEW

File: src/main/groovy/uk/nhs/digital/maurodatamapper/datadictionary/NhsDDCode.groovy [hunk 1]
```diff
@@ -79,14 +79,9 @@ class NhsDDCode {
...
             if (retiredDate) {
-                try {
-                    LocalDateTime actualRetiredDate = LocalDateTime.parse(retiredDate, DateTimeFormatter.ISO_DATE_TIME)
-                    retiredDateString = " ${actualRetiredDate.format("d MMMM yyyy")}"
-                }
-                catch (Exception exception) {
-                    // Ignore the retired date, must be in a bad format...
-                    System.err.println(exception.message)
-                }
+                // The profile field to store the retired date is just a "string" type, so just have to assume
```
Comment (OButlerOcc) [inline src/main/groovy/uk/nhs/digital/maurodatamapper/datadictionary/NhsDDCode.groovy:82]: could force it through a regex validator? If we know our valid date formats that's quite easy

**Review by OButlerOcc — CHANGES_REQUESTED** [review]
image


image


First part doesnt seem to be working.. or I retired incorrectly. Will ask monday

I might just not understand retired stuff, I can retire it, bit I can't see a retirement date on a term even thought its marked retired

And the retired element length still appears as normal

**Review by OButlerOcc — CHANGES_REQUESTED** [review]
image


image


First part doesnt seem to be working.. or I retired incorrectly. Will ask monday

**Review by OButlerOcc — APPROVED** [review]
image

Term working

image

This is working but how was it even an issue? I had to mark its place in the preview, retire it, then use the url to get back to it. Retiring the element removes it from the element list.

I'm Prob misunderstanding a use case but it now does what its supposed to.

**Comment by pjmonks** [comment]
When an issue is retired it does not appear in the usual table of contents links. It does appear under an "All Items Index" though.
